name: 030-java-springboot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-java-app:

    runs-on: ubuntu-latest

    # Optional: Set the working directory where the Java project resides (if applicable)
    defaults:
      run:
        working-directory: springbootapp

    steps:
    # Step 1: Checkout the repository to the runner's workspace
    - uses: actions/checkout@v3
    
    # Step 2: Set up Java JDK 23
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'adoptopenjdk'

    # Step 3: Build the project using Maven
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # Step 4: Run tests
    - name: Run tests
      run: mvn test --no-build --verbosity normal
    
    # Step 5: Package the Spring Boot application
    - name: Build Spring Boot app
      run: mvn package -DskipTests  # Package the Spring Boot app without running tests

    # Step 6: Optionally, run the app (this step is not usually needed for CI/CD but could be useful)
    - name: Run Spring Boot app
      run: java -jar target/*.jar  # This runs the JAR file produced after building the project
