name: 032-heroku-webapps-java-jar

env:
  HEROKU_APP_NAME: springbootapp
  JAVA_VERSION: '23'
  DISTRIBUTION: zulu

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn clean package -f ./springbootapp/pom.xml -DskipTests

      # Step 4: Upload the artifact for the deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: none
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-heroku.outputs.heroku-url }}

    steps:
      # Step 1: Download artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Step 2: Deploy to Heroku
      - name: Deploy to Heroku
        id: deploy-to-heroku
        uses: akshnz/heroku-deploy@v1.0.2
        with:
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          directory: .  # Your application directory
